### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by minecraft619** [dborth/snes9x-gx#676]
Where is the download

**Comment by scubehouse** [comment]
which download?

**Comment by minecraft619** [comment]
The download that can used on the wii? I clicked download an the wiibrew website then it took me to this github site. All I see hbc, sources, and other files. I was wanting to download a zip file that has the "apps" folder that can run through the homebrew channel on the wii.

**Comment by minecraft619** [comment]
Duh to myself, It was in the releases tab......

**Comment by filevans** [comment]
close issue then...
